# Build workflow

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Validate wrapper to prevent potential supply chain attack
  gradle-wrapper-validation:

    # Run on Ubuntu which consumes less minutes
    runs-on: ubuntu-latest

    name: Validate Gradle wrapper

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3

  build:

    # Many tests only pass on Windows
    runs-on: windows-latest

    strategy:
      matrix:
        java: [ '11', '17' ]

    name: Java ${{ matrix.Java }} build

    steps:
      - uses: actions/checkout@v4

      # Set JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      # Build
      - name: Build with Gradle
        run: >-
          ./gradlew build
          -PexcludeTests="SamplesRenderingTest.testFontArabic,SamplesRenderingTest.testVerticalText,StyleBypassRenderingTest.testVerticalText"

      # Generate modular javadocs
      - name: Modular javadocs
        run: ./gradlew modularJavadoc
