# Build workflow

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Set JDK
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      # Validate wrapper to prevent potential supply chain attack
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # Build
      - name: Build with Gradle
        run: ./gradlew build
