# Build workflow

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Validate wrapper to prevent potential supply chain attack
  gradle-wrapper-validation:
    runs-on: windows-latest

    name: Validate Gradle wrapper

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  build:
    runs-on: windows-latest

    strategy:
      matrix:
        java: [ '11', '17' ]

    name: Java ${{ matrix.Java }} build

    steps:
      - uses: actions/checkout@v2

      # Set JDK
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      # Build
      - name: Build with Gradle
        run: ./gradlew build -PexcludeTests="SamplesRenderingTest.testFontArabic,SamplesRenderingTest.testVerticalText"
