# This workflow will build a package using Gradle and then deploy it to GitHub
# packages when a release is published

name: Gradle Package

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Publish to GitHub Packages
      run: >-
        ./gradlew publish -PmavenReleaseRepoUrl="https://maven.pkg.github.com/css4j/echosvg"
        -PmavenRepoUsername=${{ github.actor }} -PmavenRepoPassword=${{ secrets.GITHUB_TOKEN }}
